services:
  db:
    container_name: postgres-jfs
    image: postgres:16
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5422:5432"
    networks:
      - db
    restart: unless-stopped

  amigoscode-api:
    container_name: amigoscode-api
    image: vmcalderingamez/spring-boot-example:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5422/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
#    command:
#      - --spring.datasource.url=jdbc:postgresql://db:5422/customer

networks:
  db:
    driver: bridge

volumes:
  db: